#!/bin/bash

if ! pgrep -x "elephant" > /dev/null; then
    elephant &
fi

if ! pgrep -f "walker --gapplication-service" > /dev/null; then
  walker --gapplication-service &
fi

exec walker --width 300 --height 500 "$@"
